#ifndef ETH_CSR_H
#define ETH_CSR_H
#include "stdint.h"
#define ETH_CSR_ETH_MAC_LOW_BIT_WIDTH 24
#define ETH_CSR_ETH_MAC_LOW_BIT_MASK 0xffffff
#define ETH_CSR_ETH_MAC_LOW_BIT_OFFSET 0
#define ETH_CSR_ETH_MAC_LOW_BYTE_WIDTH 8
#define ETH_CSR_ETH_MAC_LOW_BYTE_SIZE 8
#define ETH_CSR_ETH_MAC_LOW_BYTE_OFFSET 0x0
#define ETH_CSR_ETH_MAC_HIGH_BIT_WIDTH 24
#define ETH_CSR_ETH_MAC_HIGH_BIT_MASK 0xffffff
#define ETH_CSR_ETH_MAC_HIGH_BIT_OFFSET 0
#define ETH_CSR_ETH_MAC_HIGH_BYTE_WIDTH 8
#define ETH_CSR_ETH_MAC_HIGH_BYTE_SIZE 8
#define ETH_CSR_ETH_MAC_HIGH_BYTE_OFFSET 0x8
#define ETH_CSR_ETH_IP_BIT_WIDTH 32
#define ETH_CSR_ETH_IP_BIT_MASK 0xffffffff
#define ETH_CSR_ETH_IP_BIT_OFFSET 0
#define ETH_CSR_ETH_IP_BYTE_WIDTH 8
#define ETH_CSR_ETH_IP_BYTE_SIZE 8
#define ETH_CSR_ETH_IP_BYTE_OFFSET 0x10
#define ETH_CSR_GATEWAY_IP_BIT_WIDTH 32
#define ETH_CSR_GATEWAY_IP_BIT_MASK 0xffffffff
#define ETH_CSR_GATEWAY_IP_BIT_OFFSET 0
#define ETH_CSR_GATEWAY_IP_BYTE_WIDTH 8
#define ETH_CSR_GATEWAY_IP_BYTE_SIZE 8
#define ETH_CSR_GATEWAY_IP_BYTE_OFFSET 0x18
#define ETH_CSR_SUBNET_MASK_BIT_WIDTH 32
#define ETH_CSR_SUBNET_MASK_BIT_MASK 0xffffffff
#define ETH_CSR_SUBNET_MASK_BIT_OFFSET 0
#define ETH_CSR_SUBNET_MASK_BYTE_WIDTH 8
#define ETH_CSR_SUBNET_MASK_BYTE_SIZE 8
#define ETH_CSR_SUBNET_MASK_BYTE_OFFSET 0x20
#define ETH_CSR_RECV_MAC_LOW_BIT_WIDTH 24
#define ETH_CSR_RECV_MAC_LOW_BIT_MASK 0xffffff
#define ETH_CSR_RECV_MAC_LOW_BIT_OFFSET 0
#define ETH_CSR_RECV_MAC_LOW_BYTE_WIDTH 8
#define ETH_CSR_RECV_MAC_LOW_BYTE_SIZE 8
#define ETH_CSR_RECV_MAC_LOW_BYTE_OFFSET 0x28
#define ETH_CSR_RECV_MAC_HIGH_BIT_WIDTH 24
#define ETH_CSR_RECV_MAC_HIGH_BIT_MASK 0xffffff
#define ETH_CSR_RECV_MAC_HIGH_BIT_OFFSET 0
#define ETH_CSR_RECV_MAC_HIGH_BYTE_WIDTH 8
#define ETH_CSR_RECV_MAC_HIGH_BYTE_SIZE 8
#define ETH_CSR_RECV_MAC_HIGH_BYTE_OFFSET 0x30
#define ETH_CSR_RECV_IP_BIT_WIDTH 32
#define ETH_CSR_RECV_IP_BIT_MASK 0xffffffff
#define ETH_CSR_RECV_IP_BIT_OFFSET 0
#define ETH_CSR_RECV_IP_BYTE_WIDTH 8
#define ETH_CSR_RECV_IP_BYTE_SIZE 8
#define ETH_CSR_RECV_IP_BYTE_OFFSET 0x38
#define ETH_CSR_RECV_UDP_LENGTH_BIT_WIDTH 16
#define ETH_CSR_RECV_UDP_LENGTH_BIT_MASK 0xffff
#define ETH_CSR_RECV_UDP_LENGTH_BIT_OFFSET 0
#define ETH_CSR_RECV_UDP_LENGTH_BYTE_WIDTH 8
#define ETH_CSR_RECV_UDP_LENGTH_BYTE_SIZE 8
#define ETH_CSR_RECV_UDP_LENGTH_BYTE_OFFSET 0x40
#define ETH_CSR_SEND_MAC_LOW_BIT_WIDTH 24
#define ETH_CSR_SEND_MAC_LOW_BIT_MASK 0xffffff
#define ETH_CSR_SEND_MAC_LOW_BIT_OFFSET 0
#define ETH_CSR_SEND_MAC_LOW_BYTE_WIDTH 8
#define ETH_CSR_SEND_MAC_LOW_BYTE_SIZE 8
#define ETH_CSR_SEND_MAC_LOW_BYTE_OFFSET 0x48
#define ETH_CSR_SEND_MAC_HIGH_BIT_WIDTH 24
#define ETH_CSR_SEND_MAC_HIGH_BIT_MASK 0xffffff
#define ETH_CSR_SEND_MAC_HIGH_BIT_OFFSET 0
#define ETH_CSR_SEND_MAC_HIGH_BYTE_WIDTH 8
#define ETH_CSR_SEND_MAC_HIGH_BYTE_SIZE 8
#define ETH_CSR_SEND_MAC_HIGH_BYTE_OFFSET 0x50
#define ETH_CSR_SEND_IP_BIT_WIDTH 32
#define ETH_CSR_SEND_IP_BIT_MASK 0xffffffff
#define ETH_CSR_SEND_IP_BIT_OFFSET 0
#define ETH_CSR_SEND_IP_BYTE_WIDTH 8
#define ETH_CSR_SEND_IP_BYTE_SIZE 8
#define ETH_CSR_SEND_IP_BYTE_OFFSET 0x58
#define ETH_CSR_SEND_UDP_LENGTH_BIT_WIDTH 16
#define ETH_CSR_SEND_UDP_LENGTH_BIT_MASK 0xffff
#define ETH_CSR_SEND_UDP_LENGTH_BIT_OFFSET 0
#define ETH_CSR_SEND_UDP_LENGTH_BYTE_WIDTH 8
#define ETH_CSR_SEND_UDP_LENGTH_BYTE_SIZE 8
#define ETH_CSR_SEND_UDP_LENGTH_BYTE_OFFSET 0x60
#define ETH_CSR_SEND_PKT_BIT_WIDTH 1
#define ETH_CSR_SEND_PKT_BIT_MASK 0x1
#define ETH_CSR_SEND_PKT_BIT_OFFSET 0
#define ETH_CSR_SEND_PKT_BYTE_WIDTH 8
#define ETH_CSR_SEND_PKT_BYTE_SIZE 8
#define ETH_CSR_SEND_PKT_BYTE_OFFSET 0x68
#define ETH_CSR_CLEAR_IRQ_BIT_WIDTH 1
#define ETH_CSR_CLEAR_IRQ_BIT_MASK 0x1
#define ETH_CSR_CLEAR_IRQ_BIT_OFFSET 0
#define ETH_CSR_CLEAR_IRQ_BYTE_WIDTH 8
#define ETH_CSR_CLEAR_IRQ_BYTE_SIZE 8
#define ETH_CSR_CLEAR_IRQ_BYTE_OFFSET 0x70
#define ETH_CSR_CLEAR_ARP_BIT_WIDTH 1
#define ETH_CSR_CLEAR_ARP_BIT_MASK 0x1
#define ETH_CSR_CLEAR_ARP_BIT_OFFSET 0
#define ETH_CSR_CLEAR_ARP_BYTE_WIDTH 8
#define ETH_CSR_CLEAR_ARP_BYTE_SIZE 8
#define ETH_CSR_CLEAR_ARP_BYTE_OFFSET 0x78
typedef struct {
  uint64_t eth_mac_low;
  uint64_t eth_mac_high;
  uint64_t eth_ip;
  uint64_t gateway_ip;
  uint64_t subnet_mask;
  uint64_t recv_mac_low;
  uint64_t recv_mac_high;
  uint64_t recv_ip;
  uint64_t recv_udp_length;
  uint64_t send_mac_low;
  uint64_t send_mac_high;
  uint64_t send_ip;
  uint64_t send_udp_length;
  uint64_t send_pkt;
  uint64_t clear_irq;
  uint64_t clear_arp;
  uint64_t __reserved_0x80;
  uint64_t __reserved_0x88;
  uint64_t __reserved_0x90;
  uint64_t __reserved_0x98;
  uint64_t __reserved_0xa0;
  uint64_t __reserved_0xa8;
  uint64_t __reserved_0xb0;
  uint64_t __reserved_0xb8;
  uint64_t __reserved_0xc0;
  uint64_t __reserved_0xc8;
  uint64_t __reserved_0xd0;
  uint64_t __reserved_0xd8;
  uint64_t __reserved_0xe0;
  uint64_t __reserved_0xe8;
  uint64_t __reserved_0xf0;
  uint64_t __reserved_0xf8;
} eth_csr_t;
#endif
